require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'

Rails:
  Enabled: true

Performance:
  Enabled: true

RSpec:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude: 
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: single_quotes

RSpec/DescribeClass:
  Enabled: false

Style/Documentation:
  Enabled: false
